<?php $tipo=0;?>
<div class='col-lg-13 col-md-13 affix-sidebar'>
    <div class='col-lg-3 col-md-3 affix-sidebar'>
        <div class='sidebar-nav'>
            <div class='navbar navbar-default' role='navigation'>
                <div id='MainMenu'>
                    <a href='/dadospessoais' class='list-group-item list-group-item-success' data-parent='#MainMenu'><span class='glyphicon glyphicon-edit'></span> Home</a>
                    <?php
                    if($tipo==0){
                        echo "
                        <a href='#listar' class='list-group-item list-group-item-success' data-toggle='collapse' data-parent='#MainMenu'><span class='glyphicon glyphicon-list'></span> Listar</a>
                            <div class='collapse' id='listar'>
                                <ul type='none'>
                                    <li><a href='/alunos/main'><span class='glyphicon glyphicon-folder-open'></span> Aluno</a></li>
                                    <li><a href='/cargos/main'><span class='glyphicon glyphicon-folder-open'></span> Cargo Funcionario</a></li>
                                    <li><a href='/cursos/main'><span class='glyphicon glyphicon-folder-open'></span> Curso</a></li>
                                    <li><a href='/dadospessoais/main'><span class='glyphicon glyphicon-folder-open'></span> Dados Pessoais</a></li>
                                    <li><a href='/funcionarios/main'><span class='glyphicon glyphicon-folder-open'></span> Funcionario</a></li>
                                    <li><a href='/gerenciadores/main'><span class='glyphicon glyphicon-folder-open'></span> Gerenciador</a></li>
                                    <li><a href='/materias/main'><span class='glyphicon glyphicon-folder-open'></span> Materia</a></li>
                                    <li><a href='/series/main'><span class='glyphicon glyphicon-folder-open'></span> Serie</a></li>
                                    <li><a href='/usuarios/main'><span class='glyphicon glyphicon-folder-open'></span> Usuario</a></li>
                                </ul>
                            </div>
                        ";
                    }
                    ?>


                    <a href='#editarperfil' class='list-group-item list-group-item-success' data-toggle='collapse' data-parent='#MainMenu'><span class='glyphicon glyphicon-edit'></span> Editar Perfil</a>
                    <a href='#badges' class='list-group-item list-group-item-success' data-toggle='collapse' data-parent='#MainMenu'><span class='glyphicon glyphicon-calendar'></span> WithBadges <span class='badge pull-right'>42</span></a>
                    <a href='/' class='list-group-item list-group-item-success' data-parent='#MainMenu'><span class='glyphicon glyphicon-log-out'></span> Logout</a>

                </div>
            </div>
        </div>
    </div>
</div>

<div class='col-lg-9 col-md-9 affix-sidebar'>
    <div class='panel panel-primary'>
        <div class='panel-heading'>
            <div class='panel-title'>
                Editar Pessoa ID <?php echo $this->id; ?>
            </div>
        </div>
        <?php
        // objeto form contato
        $formDadosPessoais = $this->formDadosPessoais;
        // preparar elementos do formulário
        $formDadosPessoais->prepare();
        // configurar url formulário
        $formDadosPessoais->setAttribute('action', $this->url('dadospessoais', array('action' => 'atualizar')));
        ?>

        <?php // renderiza html <form> com atributos configurados no objeto ?>
        <?php echo $this->form()->openTag($formDadosPessoais) ?>
        <div class='panel-body'>
            <div class='form-group'>
                <label for='inputNomePessoa' class='col-lg-2 col-md-2 control-label'>Nome Completo*:</label>
                <div class='col-lg-10 col-md-10'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formDadosPessoais->get('nome_pessoa'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formDadosPessoais->get('nome_pessoa'));
                    ?>
                </div>
            </div>

            <div class='form-group'>
                <label for='inputCpf' class='col-lg-2 col-md-2 control-label'>Cpf*:</label>
                <div class='col-lg-4 col-md-4'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formDadosPessoais->get('cpf'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formDadosPessoais->get('cpf'));
                    ?>
                </div>

                <label for='inputIdentidade' class='col-lg-1 col-md-1 control-label'>Identidade*:</label>
                <div class='col-lg-5 col-md-5'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formDadosPessoais->get('identidade'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formDadosPessoais->get('identidade'));
                    ?>
                </div>
            </div>

            <div class='form-group'>
                <label for='inputEndereco' class='col-lg-2 col-md-2 control-label'>Endereço:</label>
                <div class='col-lg-10 col-md-10'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formDadosPessoais->get('endereco'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formDadosPessoais->get('endereco'));
                    ?>
                </div>
            </div>


            <div class='form-group'>
                <label for='inputLogradouro' class='col-lg-2 col-md-2 control-label'>Logradouro:</label>
                <div class='col-lg-7 col-md-7'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formDadosPessoais->get('logradouro'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formDadosPessoais->get('logradouro'));
                    ?>
                </div>

                <label for='inputNumero' class='col-lg-1 col-md-1 control-label'>Numero:</label>
                <div class='col-lg-2 col-md-2'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formDadosPessoais->get('numero'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formDadosPessoais->get('numero'));
                    ?>
                </div>
            </div>

            <div class='form-group'>
                <label for='inputBairro' class='col-lg-2 col-md-2 control-label'>Bairro:</label>
                <div class='col-lg-6 col-md-6'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formDadosPessoais->get('bairro'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formDadosPessoais->get('bairro'));
                    ?>
                </div>

                <label for='inputApto' class='col-lg-2 col-md-2 control-label'>Apto:</label>
                <div class='col-lg-2 col-md-2'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formDadosPessoais->get('apto'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formDadosPessoais->get('apto'));
                    ?>
                </div>
            </div>

            <div class='form-group'>

                <label for='inputCidade' class='col-lg-2 col-md-2 control-label'>Cidade:</label>
                <div class='col-lg-3 col-md-3'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formDadosPessoais->get('cidade'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formDadosPessoais->get('cidade'));
                    ?>
                </div>

                <label for='inputEstado' class='col-lg-1 col-md-1 control-label'>Estado:</label>
                <div class='col-lg-3 col-md-3'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formDadosPessoais->get('estado'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formDadosPessoais->get('estado'));
                    ?>
                </div>

                <label for='inputCep' class='col-lg-1 col-md-1 control-label'>Cep:</label>
                <div class='col-lg-2 col-md-2'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formDadosPessoais->get('cep'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formDadosPessoais->get('cep'));
                    ?>
                </div>
            </div>

            <div class='form-group'>
                <label for='inputEmail' class='col-lg-2 col-md-2 control-label'>Email*:</label>
                <div class='col-lg-5 col-md-5'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formDadosPessoais->get('email'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formDadosPessoais->get('email'));
                    ?>
                </div>

                <label for='inputDataNasc' class='col-lg-2 col-md-2 control-label'>Data de Nascimento*:</label>
                <div class='col-lg-3 col-md-3'>
                    <?php
                    // renderiza html input
                    echo $this->formDate($formDadosPessoais->get('data_nasc'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formDadosPessoais->get('data_nasc'));
                    ?>
                </div>
            </div>

            <div class='form-group'>
                <label for='inputTelefonePrincipal' class='col-lg-2 col-md-2 control-label'>Tel. Principal*:</label>
                <div class='col-lg-4  col-md-4'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formDadosPessoais->get('telefone_principal'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formDadosPessoais->get('telefone_principal'));
                    ?>
                </div>

                <label for='inputTelefoneSecundario' class='col-lg-2 col-md-2 control-label'>Tel. Secundário:</label>
                <div class='col-lg-4  col-md-4'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formDadosPessoais->get('telefone_secundario'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formDadosPessoais->get('telefone_secundario'));
                    ?>
                </div>
            </div>

            <div class='form-group'>
                <label for='radSexo' class='col-lg-2 col-md-2 control-label'>Sexo*:</label>
                <div class='col-lg-2  col-md-2' id='radSexo'>
                    <?php
                    // renderiza html input
                    echo $this->FormRadio($formDadosPessoais->get('sexo'));//colocar como name no form.php

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formDadosPessoais->get('sexo'));
                    ?>
                </div>

                <label for='radSituacao' class='col-lg-4 col-md-4 control-label'>Situacao Atual*:</label>
                <div class='col-lg-2  col-md-2' id='radSituacao'>
                    <?php
                    // renderiza html input
                    echo $this->FormRadio($formDadosPessoais->get('situacao'));//colocar como name no form.php

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formDadosPessoais->get('situacao'));
                    ?>
                </div>
            </div>


            <!--<div class='form-group'>
            <label for='inputCaptcha' class='col-lg-2 col-md-2 control-label'>Verificação*:</label>
            <div class='col-lg-9  col-md-9' id='captcha'>
                <?php
            // renderiza captcha
            /*echo $this->formCaptcha(formDadosPessoais->get('captcha'));

            // renderiza elemento de erro
            echo $this->formElementErrors()
                ->setMessageOpenFormat("<small class='text-danger'>")
                ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                ->setMessageCloseString('</small>')
                ->render(formDadosPessoais->get('captcha'));*/
            ?>
            </div>
        </div>-->
        </div>
        <div class='panel-footer'>
            <?php
            // renderiza html input hidden para id
            echo $this->formHidden($formDadosPessoais->get('id_pessoa'));
            // renderiza html input hidden csrf
            //echo $this->formElement($formDadosPessoais->get('security'));
            ?>

            <button type='submit' class='btn btn-primary'>Salvar Dados</button>
            <a href="<?php echo $this->url('dadospessoais', ['action' => 'main']); ?>" class="btn btn-default">Voltar</a>
        </div>

        <?php // renderiza html </form> ?>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>

