<?php $tipo=0;?>
<div class='col-lg-13 col-md-13 affix-sidebar'>
    <div class='col-lg-3 col-md-3 affix-sidebar'>
        <div class='sidebar-nav'>
            <div id='MainMenu'>
                <a href='/dadospessoais' class='list-group-item list-group-item-success' data-parent='#MainMenu'><span class='glyphicon glyphicon-home'></span> Home</a>
                <?php
                if($tipo==0){
                    echo "
                        <a href='#listar' class='list-group-item list-group-item-success' data-toggle='collapse' data-parent='#MainMenu'><span class='glyphicon glyphicon-list'></span> Listar</a>
                            <div class='collapse' id='listar'>
                                <ul type='none'>
                                    <li><a href='/alunos/main'><span class='glyphicon glyphicon-folder-open'></span> Aluno</a></li>
                                    <li><a href='/cargos/main'><span class='glyphicon glyphicon-folder-open'></span> Cargo Funcionario</a></li>
                                    <li><a href='/cursos/main'><span class='glyphicon glyphicon-folder-open'></span> Curso</a></li>
                                    <li><a href='/dadospessoais/main'><span class='glyphicon glyphicon-folder-open'></span> Dados Pessoais</a></li>
                                    <li><a href='/funcionarios/main'><span class='glyphicon glyphicon-folder-open'></span> Funcionario</a></li>
                                    <li><a href='/gerenciadores/main'><span class='glyphicon glyphicon-folder-open'></span> Gerenciador</a></li>
                                    <li><a href='/materias/main'><span class='glyphicon glyphicon-folder-open'></span> Materia</a></li>
                                    <li><a href='/series/main'><span class='glyphicon glyphicon-folder-open'></span> Serie</a></li>
                                    <li><a href='/usuarios/main'><span class='glyphicon glyphicon-folder-open'></span> Usuario</a></li>
                                </ul>
                            </div>
                        ";
                }
                ?>

                <a href='#editarperfil' class='list-group-item list-group-item-success' data-toggle='collapse' data-parent='#MainMenu'><span class='glyphicon glyphicon-edit'></span> Editar Perfil</a>
                <a href='/' class='list-group-item list-group-item-success' data-parent='#MainMenu'><span class='glyphicon glyphicon-log-out'></span> Logout</a>

            </div>
        </div>
    </div>

    <div class='col-lg-9 col-md-9 affix-sidebar'>
        <iframe src='https://calendar.google.com/calendar/embed?src=5krup7r5tlnbest542uv34bss0%40group.calendar.google.com&ctz=America/Sao_Paulo' style='border: 0' width='800' height='600' frameborder='0' scrolling='no'></iframe>
    </div>
</div>