<?php $tipo=0;?>
<div class='col-lg-13 col-md-13 affix-sidebar'>
    <div class='col-lg-3 col-md-3 affix-sidebar'>
        <div class='sidebar-nav'>
            <div class='navbar navbar-default' role='navigation'>
                <div id='MainMenu'>
                    <a href='/dadospessoais' class='list-group-item list-group-item-success' data-parent='#MainMenu'><span class='glyphicon glyphicon-edit'></span> Home</a>
                    <?php
                    if($tipo==0){
                        echo "
                        <a href='#listar' class='list-group-item list-group-item-success' data-toggle='collapse' data-parent='#MainMenu'><span class='glyphicon glyphicon-list'></span> Listar</a>
                            <div class='collapse' id='listar'>
                                <ul type='none'>
                                    <li><a href='/alunos/main'><span class='glyphicon glyphicon-folder-open'></span> Aluno</a></li>
                                    <li><a href='/cargos/main'><span class='glyphicon glyphicon-folder-open'></span> Cargo Funcionario</a></li>
                                    <li><a href='/cursos/main'><span class='glyphicon glyphicon-folder-open'></span> Curso</a></li>
                                    <li><a href='/dadospessoais/main'><span class='glyphicon glyphicon-folder-open'></span> Dados Pessoais</a></li>
                                    <li><a href='/funcionarios/main'><span class='glyphicon glyphicon-folder-open'></span> Funcionario</a></li>
                                    <li><a href='/gerenciadores/main'><span class='glyphicon glyphicon-folder-open'></span> Gerenciador</a></li>
                                    <li><a href='/materias/main'><span class='glyphicon glyphicon-folder-open'></span> Materia</a></li>
                                    <li><a href='/series/main'><span class='glyphicon glyphicon-folder-open'></span> Serie</a></li>
                                    <li><a href='/usuarios/main'><span class='glyphicon glyphicon-folder-open'></span> Usuario</a></li>
                                </ul>
                            </div>
                        ";
                    }
                    ?>

                    <a href='#editarperfil' class='list-group-item list-group-item-success' data-toggle='collapse' data-parent='#MainMenu'><span class='glyphicon glyphicon-edit'></span> Editar Perfil</a>
                    <a href='#badges' class='list-group-item list-group-item-success' data-toggle='collapse' data-parent='#MainMenu'><span class='glyphicon glyphicon-calendar'></span> WithBadges <span class='badge pull-right'>42</span></a>
                    <a href='/' class='list-group-item list-group-item-success' data-parent='#MainMenu'><span class='glyphicon glyphicon-log-out'></span> Logout</a>

                </div>
            </div>
        </div>
    </div>
</div>

<div class='col-lg-9 col-md-9 affix-sidebar'>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="panel-title">
                Novo Cargo Funcionário
            </div>
        </div>
        <?php
        // objeto form contato
        $formCargos = $this->formCargos;
        // preparar elementos do formulário
        $formCargos->prepare();
        // configurar url formulário
        $formCargos->setAttribute('action', $this->url('cargos', array('action' => 'adicionar')));
        ?>

        <?php // renderiza html <form> com atributos configurados no objeto ?>
        <?php echo $this->form()->openTag($formCargos) ?>
        <div class="panel-body">
            <div class="form-group">
                <label for="inputNomeCargo" class="col-lg-2 col-md-2 control-label">Cargo do funcionario*:</label>
                <div class="col-lg-9 col-md-9">
                    <?php
                    // renderiza html input
                    echo $this->formInput($formCargos->get('nome_cargo'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formCargos->get('nome_cargo'));
                    ?>
                </div>
            </div>


            <!--<div class="form-group">
            <label for="inputCaptcha" class="col-lg-2 col-md-2 control-label">Verificação*:</label>
            <div class="col-lg-9  col-md-9" id="captcha">
                <?php
            // renderiza captcha
            /*echo $this->formCaptcha($formCargos->get('captcha'));

            // renderiza elemento de erro
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<small class="text-danger">')
                ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                ->setMessageCloseString('</small>')
                ->render($formCargos->get('captcha'));*/
            ?>
            </div>
        </div>-->
        </div>
        <div class="panel-footer">
            <?php
            // renderiza html input hidden para id
            echo $this->formHidden($formCargos->get('id_cargo'));
            // renderiza html input hidden csrf
            //echo $this->formElement($formCargos->get('security'));
            ?>

            <button type="submit" class="btn btn-primary">Salvar Dados</button>
            <a href="<?php echo $this->url('cargos', ['action' => 'main']); ?>" class="btn btn-default">Voltar</a>
        </div>

        <?php // renderiza html </form> ?>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>
