<?php $tipo=0;?>
<div class='col-lg-13 col-md-13 affix-sidebar'>
    <div class='col-lg-3 col-md-3 affix-sidebar'>
        <div class='sidebar-nav'>
            <div class='navbar navbar-default' role='navigation'>
                <div id='MainMenu'>
                    <a href='/alunos' class='list-group-item list-group-item-success' data-parent='#MainMenu'><span class='glyphicon glyphicon-edit'></span> Home</a>
                    <?php
                    if($tipo==0){
                        echo "
                        <a href='#listar' class='list-group-item list-group-item-success' data-toggle='collapse' data-parent='#MainMenu'><span class='glyphicon glyphicon-list'></span> Listar</a>
                            <div class='collapse' id='listar'>
                                <ul type='none'>
                                    <li><a href='/alunos/main'><span class='glyphicon glyphicon-folder-open'></span> Aluno</a></li>
                                    <li><a href='/cargos/main'><span class='glyphicon glyphicon-folder-open'></span> Cargo Funcionario</a></li>
                                    <li><a href='/cursos/main'><span class='glyphicon glyphicon-folder-open'></span> Curso</a></li>
                                    <li><a href='/dadospessoais/main'><span class='glyphicon glyphicon-folder-open'></span> Dados Pessoais</a></li>
                                    <li><a href='/funcionarios/main'><span class='glyphicon glyphicon-folder-open'></span> Funcionario</a></li>
                                    <li><a href='/gerenciadores/main'><span class='glyphicon glyphicon-folder-open'></span> Gerenciador</a></li>
                                    <li><a href='/materias/main'><span class='glyphicon glyphicon-folder-open'></span> Materia</a></li>
                                    <li><a href='/series/main'><span class='glyphicon glyphicon-folder-open'></span> Serie</a></li>
                                    <li><a href='/usuarios/main'><span class='glyphicon glyphicon-folder-open'></span> Usuario</a></li>
                                </ul>
                            </div>
                        ";
                    }
                    ?>


                    <a href='#editarperfil' class='list-group-item list-group-item-success' data-toggle='collapse' data-parent='#MainMenu'><span class='glyphicon glyphicon-edit'></span> Editar Perfil</a>
                    <a href='#badges' class='list-group-item list-group-item-success' data-toggle='collapse' data-parent='#MainMenu'><span class='glyphicon glyphicon-calendar'></span> WithBadges <span class='badge pull-right'>42</span></a>
                    <a href='/' class='list-group-item list-group-item-success' data-parent='#MainMenu'><span class='glyphicon glyphicon-log-out'></span> Logout</a>

                </div>
            </div>
        </div>
    </div>
</div>

<div class='col-lg-9 col-md-9 affix-sidebar'>
    <div class='panel panel-primary'>
        <div class='panel-heading'>
            <div class='panel-title'>
                Editar Aluno <?php echo $this->id; ?>
            </div>
        </div>
        <?php
        // objeto form aluno
        $formAlunos = $this->formAlunos;
        // preparar elementos do formulário
        $formAlunos->prepare();
        // configurar url formulário
        $formAlunos->setAttribute('action', $this->url('alunos', ['action' => 'atualizar']));
        ?>

        <?php // renderiza html <form> com atributos configurados no objeto ?>
        <?php echo $this->form()->openTag($formAlunos) ?>
        <div class="panel-body">
            <div class="form-group">
                <label for="inputNomeAluno" class="col-lg-2 col-md-2 control-label">Nome Do Aluno*:</label>
                <div class="col-lg-6 col-md-6">
                    <?php
                    // renderiza html input
                    echo $this->formInput($formAlunos->get('nome_aluno'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formAlunos->get('nome_aluno'));
                    ?>
                </div>

                <label for="inputMatriculaAluno" class="col-lg-1 col-md-1 control-label">Matrícula*:</label>
                <div class="col-lg-3 col-md-3">
                    <?php
                    // renderiza html input
                    echo $this->formInput($formAlunos->get('matricula_aluno'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formAlunos->get('matricula_aluno'));
                    ?>
                </div>
            </div>

            <div class="form-group">
                <label for="inputCursoAluno" class="col-lg-2 col-md-2 control-label">Curso*:</label>
                <div class="col-lg-4 col-md-4">
                    <?php
                    // renderiza html input
                    echo $this->formSelect($formAlunos->get('curso_aluno'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formAlunos->get('curso_aluno'));
                    ?>
                </div>

                <label for="inputSerieAluno" class="col-lg-2 col-md-2 control-label">Série*:</label>
                <div class="col-lg-4 col-md-4">
                    <?php
                    // renderiza html input
                    echo $this->formSelect($formAlunos->get('serie_aluno'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formAlunos->get('serie_aluno'));
                    ?>
                </div>
            </div>

            <div class="form-group">
                <label for="inputMateriaAluno" class="col-lg-2 col-md-2 control-label">Matéria*:</label>
                <div class="col-lg-4 col-md-4">
                    <?php
                    // renderiza html input
                    echo $this->formSelect($formAlunos->get('materia_aluno'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formAlunos->get('materia_aluno'));
                    ?>
                </div>

                <label for="inputProfessorAluno" class="col-lg-2 col-md-2 control-label">Professor*:</label>
                <div class="col-lg-4 col-md-4">
                    <?php
                    // renderiza html input
                    echo $this->formSelect($formAlunos->get('professor_aluno'));

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($formAlunos->get('professor_aluno'));
                    ?>
                </div>
            </div>

            <div class="form-group">
                <label for='inputProva1' class='col-lg-2 col-md-2 control-label'>Prova 1:</label>
                <div class='col-lg-2  col-md-2' id='inputProva1'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formAlunos->get('prova1'));//colocar como name no form.php

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formAlunos->get('prova1'));
                    ?>
                </div>

                <label for='inputProva2' class='col-lg-2 col-md-2 control-label'>Prova 2:</label>
                <div class='col-lg-2  col-md-2' id='inputProva2'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formAlunos->get('prova2'));//colocar como name no form.php

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formAlunos->get('prova2'));
                    ?>
                </div>
            </div>

            <div class="form-group">
                <label for='inputProva3' class='col-lg-2 col-md-2 control-label'>Prova 3:</label>
                <div class='col-lg-2  col-md-2' id='inputProva3'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formAlunos->get('prova3'));//colocar como name no form.php

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formAlunos->get('prova3'));
                    ?>
                </div>

                <label for='inputProva4' class='col-lg-2 col-md-2 control-label'>Prova 4:</label>
                <div class='col-lg-2  col-md-2' id='inputProva4'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formAlunos->get('prova4'));//colocar como name no form.php

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formAlunos->get('prova4'));
                    ?>
                </div>
            </div>

            <div class="form-group">
                <label for='inputTrabalho1' class='col-lg-2 col-md-2 control-label'>Trabalho 1:</label>
                <div class='col-lg-2  col-md-2' id='inputTrabalho1'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formAlunos->get('trabalho1'));//colocar como name no form.php

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formAlunos->get('trabalho1'));
                    ?>
                </div>

                <label for='inputTrabalho2' class='col-lg-2 col-md-2 control-label'>Trabalho 2:</label>
                <div class='col-lg-2  col-md-2' id='inputTrabalho2'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formAlunos->get('trabalho2'));//colocar como name no form.php

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formAlunos->get('trabalho2'));
                    ?>
                </div>
            </div>

            <div class="form-group">
                <label for='inputTrabalho3' class='col-lg-2 col-md-2 control-label'>Trabalho 3:</label>
                <div class='col-lg-2  col-md-2' id='inputTrabalho3'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formAlunos->get('trabalho3'));//colocar como name no form.php

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formAlunos->get('trabalho3'));
                    ?>
                </div>

                <label for='inputTrabalho4' class='col-lg-2 col-md-2 control-label'>Trabalho 4:</label>
                <div class='col-lg-2  col-md-2' id='inputTrabalho4'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formAlunos->get('trabalho4'));//colocar como name no form.php

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formAlunos->get('trabalho4'));
                    ?>
                </div>
            </div>

            <div class="form-group">
                <label for='radSituacaoAluno' class='col-lg-2 col-md-2 control-label'>Situacao Aluno*:</label>
                <div class='col-lg-2  col-md-2' id='radSituacaoAluno'>
                    <?php
                    // renderiza html input
                    echo $this->FormRadio($formAlunos->get('situacao_aluno'));//colocar como name no form.php

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formAlunos->get('situacao_aluno'));
                    ?>
                </div>

                <label for='inputFaltas' class='col-lg-2 col-md-2 control-label'>Faltas:</label>
                <div class='col-lg-2  col-md-2' id='inputFaltas'>
                    <?php
                    // renderiza html input
                    echo $this->formInput($formAlunos->get('faltas'));//colocar como name no form.php

                    // renderiza elemento de erro
                    echo $this->formElementErrors()
                        ->setMessageOpenFormat("<small class='text-danger'>")
                        ->setMessageSeparatorString("</small><br/><small class='text-danger'>")
                        ->setMessageCloseString('</small>')
                        ->render($formAlunos->get('faltas'));
                    ?>
                </div>
            </div>


            <!--<div class="form-group">
            <label for="inputCaptcha" class="col-lg-2 col-md-2 control-label">Verificação*:</label>
            <div class="col-lg-9  col-md-9" id="captcha">
                <?php
            // renderiza captcha
            /*echo $this->formCaptcha($formAlunos->get('captcha'));

            // renderiza elemento de erro
            echo $this->formElementErrors()
                ->setMessageOpenFormat('<small class="text-danger">')
                ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                ->setMessageCloseString('</small>')
                ->render($formAlunos->get('captcha'));*/
            ?>
            </div>
        </div>-->
        </div>
        <div class="panel-footer">
            <?php
            // renderiza html input hidden para id
            echo $this->formHidden($formAlunos->get('id_aluno'));
            // renderiza html input hidden csrf
            //echo $this->formElement($formAlunos->get('security'));
            ?>

            <button type="submit" class="btn btn-primary">Salvar Dados</button>
            <a href="<?php echo $this->url('alunos', ['action' => 'main']); ?>" class="btn btn-default">Voltar</a>
        </div>

        <?php // renderiza html </form> ?>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>

