<?php $tipo=0;?>
<div class='col-lg-13 col-md-13 affix-sidebar'>
    <div class='col-lg-3 col-md-3 affix-sidebar'>
        <div class='sidebar-nav'>
            <div class='navbar navbar-default' role='navigation'>
                <div id='MainMenu'>
                    <a href='/funcionarios' class='list-group-item list-group-item-success' data-parent='#MainMenu'><span class='glyphicon glyphicon-edit'></span> Home</a>
                    <?php
                    if($tipo==0){
                        echo "
                        <a href='#listar' class='list-group-item list-group-item-success' data-toggle='collapse' data-parent='#MainMenu'><span class='glyphicon glyphicon-list'></span> Listar</a>
                            <div class='collapse' id='listar'>
                                <ul type='none'>
                                    <li><a href='/alunos/main'><span class='glyphicon glyphicon-folder-open'></span> Aluno</a></li>
                                    <li><a href='/cargos/main'><span class='glyphicon glyphicon-folder-open'></span> Cargo Funcionario</a></li>
                                    <li><a href='/cursos/main'><span class='glyphicon glyphicon-folder-open'></span> Curso</a></li>
                                    <li><a href='/dadospessoais/main'><span class='glyphicon glyphicon-folder-open'></span> Dados Pessoais</a></li>
                                    <li><a href='/funcionarios/main'><span class='glyphicon glyphicon-folder-open'></span> Funcionario</a></li>
                                    <li><a href='/gerenciadores/main'><span class='glyphicon glyphicon-folder-open'></span> Gerenciador</a></li>
                                    <li><a href='/materias/main'><span class='glyphicon glyphicon-folder-open'></span> Materia</a></li>
                                    <li><a href='/series/main'><span class='glyphicon glyphicon-folder-open'></span> Serie</a></li>
                                    <li><a href='/usuarios/main'><span class='glyphicon glyphicon-folder-open'></span> Usuario</a></li>
                                </ul>
                            </div>
                        ";
                    }
                    ?>

                    <a href='#editarperfil' class='list-group-item list-group-item-success' data-toggle='collapse' data-parent='#MainMenu'><span class='glyphicon glyphicon-edit'></span> Editar Perfil</a>
                    <a href='#badges' class='list-group-item list-group-item-success' data-toggle='collapse' data-parent='#MainMenu'><span class='glyphicon glyphicon-calendar'></span> WithBadges <span class='badge pull-right'>42</span></a>
                    <a href='/' class='list-group-item list-group-item-success' data-parent='#MainMenu'><span class='glyphicon glyphicon-log-out'></span> Logout</a>

                </div>
            </div>
        </div>
    </div>
</div>

<div class='col-lg-9 col-md-9 affix-sidebar'>
    <div class='topo-table'>
        <a href='<?php echo $this->url('funcionarios', array('action' => 'novo'))?>' class='btn btn-success' title='Novo'><span class='glyphicon glyphicon-plus'></span></a>

        <div class='btn-group' title='Quantidades por Página'>
            <button type='button' class='btn btn-default'><?php echo $this->itens_pagina; ?></button>
            <button type='button' class='btn btn-default dropdown-toggle' data-toggle='dropdown'>
                <span class='caret'></span>
            </button>
            <ul class='dropdown-menu pull-right' style='min-width: 75px' role='menu'>
                <?php foreach (['005', '010', '025', '050', '100'] as $value): ?>
                    <li class='<?php echo ($this->itens_pagina == $value ? 'active' : ''); ?>'><a href='<?php echo $this->url('funcionarios', ['action' => 'main'], ['query' => ['pagina' => $this->pagina_atual, 'coluna_nome' => $coluna_nome, 'coluna_sort' => $this->coluna_sort, 'itens_pagina' => $value, 'search' => $this->search]])?>'><?php echo $value;  ?></a></li>
                <?php endforeach;?>
            </ul>
        </div>

        <form class='form-inline pull-right' role='form'>
            <div class='form-group'>
                <label class='sr-only' for='localizar'>Buscar...</label>
                <input type='search' name='search' value='<?php echo $this->search; ?>' class='form-control typeahead' id='localizar' placeholder='Bucar...' autocomplete='off'>
            </div>
            <button type='submit' class='btn btn-default'><span class='glyphicon glyphicon-search'></span></button>
        </form>
    </div>

    <br />

    <div class='corpo-table'>
        <table class='table table-striped table-bordered table-hover'>
            <thead>
            <?php echo $this->partial('partial/colunas_sort_funcionario'); ?>
            </thead>

            <tbody>
            <?php foreach ($this->funcionarios as $funcionario) : ?>
                <tr>
                    <td class='text-center'><?php echo $this->filter_funcionario($funcionario)->idFuncionario(); ?></td>
                    <td><?php echo $this->filter_funcionario($funcionario)->nomeFuncionario(); ?></td>
                    <td><?php echo $this->filter_funcionario($funcionario)->cargoFuncionario(); ?></td>
                    <td><?php echo $this->filter_funcionario($funcionario)->formacaoFuncionario(); ?></td>
                    <td><?php echo $this->filter_funcionario($funcionario)->especiadadeFuncionario(); ?></td>
                    <td>
                        <a class='btn btn-xs btn-info' title='Visualizar' href='<?php echo $this->url('funcionarios', array('action' => 'detalhes', 'id' => $funcionario->id_funcionario,)); ?>'><span class='glyphicon glyphicon-new-window'></span></a>
                        <a class='btn btn-xs btn-warning' title='Editar' href='<?php echo $this->url('funcionarios', array('action' => 'editar', 'id' => $funcionario->id_funcionario,)); ?>'><span class='glyphicon glyphicon-edit'></span></a>
                        <a class='btn btn-xs btn-danger' title='Deletar' href='<?php echo $this->url('funcionarios', array('action' => 'deletar', 'id' => $funcionario->id_funcionario,)); ?>'><span class='glyphicon glyphicon-floppy-remove'></span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

        <?php
        // controle de paginação
        echo $this->paginationControl(
        // objeto contentdo os funcionarios
            $this->funcionarios,

            // tipo de style da paginação
            'Sliding',

            // partial que vai conter o html da paginação
            [/*path*/ 'partial/paginator.phtml', /*modulo*/ 'Funcionario'],

            // link rotas da paginação
            ['route' => 'funcionarios']
        );
        ?>
    </div>
</div>
</div>

<?php $this->headScript()->captureStart(); ?>
$(function(){
    // variável para conter a url deletar
    var url_deletar     = '<?php echo $this->url('funcionarios', array("action" => "deletar")); ?>' + '/';

    // qualquer link que tiver a url deletar vai sofrer um evento quando for clicada
    $("a[href*='" + url_deletar + "']").click(function (event) {
        // variável contendo o id referente ao botão clicado
        var funcionario_id  = $(this).attr('href').split(url_deletar).pop();
        // variável contendo mensagem da janela
        var mensagem = "Deseja realmente apagar o funcionario de ID " + funcionario_id + "?";
        // variável com resposta da mensagem colocada na janela
        var confirmacao = confirm(mensagem);

        // se a confirmação for false o fluxo é interrompido
        if (!confirmacao)
            // elimar o evendo do botão clicado
            event.preventDefault();
    });
});
<?php $this->headScript()->captureEnd(); ?>