<?php
/**
 * Created by PhpStorm.
 * User: CristianoGD
 * Date: 30/09/2015
 * Time: 13:32
 */

$estruturaColuna = function($label, $coluna_nome) {
    $html = '';
    $html .= "<a href='{$this->url('dadospessoais', ['action' => 'main'], ['query' => ['pagina' => $this->pagina_atual, 'coluna_nome' => $coluna_nome, 'coluna_sort' => ($this->coluna_nome != $coluna_nome ? 'ASC' : ($this->coluna_sort == 'DESC' ? 'ASC' : 'DESC')), 'itens_pagina' => $this->itens_pagina, 'search' => $this->search]])}'>";

    if ($this->coluna_nome == $coluna_nome) {
        $icon = $this->coluna_sort == 'ASC' ? '' : '-alt';
        $html .= "<span class='glyphicon glyphicon-sort-by-attributes{$icon}'></span> ";
    }

    $html .= $label;

    return $html;
};
?>
<tr>
    <th>
        <?php echo $estruturaColuna('Nº Registro', 'id_pessoa'); ?>
    </th>
    <th>
        <?php echo $estruturaColuna('Nome', 'nome_pessoa'); ?>
    </th>
    <th>
        <?php echo $estruturaColuna('Tel. Principal', 'telefone_principal'); ?>
    </th>
    <th>
        <?php echo $estruturaColuna('CPF', 'cpf'); ?>
    </th>
    <th>
        <?php echo $estruturaColuna('Dt. Nasc', 'data_nasc'); ?>
    </th>
    <th>Ação</th>
</tr>