<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Novo Estudante
        </div>
    </div>
    <?php
    // objeto form contato
    $formEstudante = $this->formEstudante;
    // preparar elementos do formulário
    $formEstudante->prepare();
    // configurar url formulário
    $formEstudante->setAttribute('action', $this->url('main', array('action' => 'adicionar')));
    ?>

    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($formEstudante) ?>
    <div class="panel-body">
        <div class="form-group">
            <label for="inputNome" class="col-lg-2 col-md-2 control-label">Nome Completo*:</label>
            <div class="col-lg-10 col-md-10">
                <?php
                // renderiza html input
                echo $this->formInput($formEstudante->get('nome_pessoa'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formEstudante->get('nome_pessoa'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputCpf" class="col-lg-2 col-md-2 control-label">Cpf*:</label>
            <div class="col-lg-4 col-md-4">
                <?php
                // renderiza html input
                echo $this->formInput($formEstudante->get('cpf'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formEstudante->get('cpf'));
                ?>
            </div>

            <label for="inputIdentidade" class="col-lg-1 col-md-1 control-label">Identidade*:</label>
            <div class="col-lg-5 col-md-5">
                <?php
                // renderiza html input
                echo $this->formInput($formEstudante->get('identidade'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formEstudante->get('identidade'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputEndereco" class="col-lg-2 col-md-2 control-label">Endereço:</label>
            <div class="col-lg-10 col-md-10">
                <?php
                // renderiza html input
                echo $this->formInput($formEstudante->get('endereco'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formEstudante->get('endereco'));
                ?>
            </div>
        </div>


        <div class="form-group">
            <label for="inputLogradouro" class="col-lg-2 col-md-2 control-label">Logradouro:</label>
            <div class="col-lg-7 col-md-7">
                <?php
                // renderiza html input
                echo $this->formInput($formEstudante->get('logradouro'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formEstudante->get('logradouro'));
                ?>
            </div>

            <label for="inputNumero" class="col-lg-1 col-md-1 control-label">Numero:</label>
            <div class="col-lg-2 col-md-2">
                <?php
                // renderiza html input
                echo $this->formInput($formEstudante->get('numero'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formEstudante->get('numero'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputBairro" class="col-lg-2 col-md-2 control-label">Bairro:</label>
            <div class="col-lg-6 col-md-6">
                <?php
                // renderiza html input
                echo $this->formInput($formEstudante->get('bairro'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formEstudante->get('bairro'));
                ?>
            </div>

            <label for="inputApto" class="col-lg-2 col-md-2 control-label">Apto:</label>
            <div class="col-lg-2 col-md-2">
                <?php
                // renderiza html input
                echo $this->formInput($formEstudante->get('apto'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formEstudante->get('apto'));
                ?>
            </div>
        </div>

        <div class="form-group">

            <label for="inputCidade" class="col-lg-2 col-md-2 control-label">Cidade:</label>
            <div class="col-lg-3 col-md-3">
                <?php
                // renderiza html input
                echo $this->formInput($formEstudante->get('cidade'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formEstudante->get('cidade'));
                ?>
            </div>

            <label for="inputEstado" class="col-lg-1 col-md-1 control-label">Estado:</label>
            <div class="col-lg-3 col-md-3">
                <?php
                // renderiza html input
                echo $this->formInput($formEstudante->get('estado'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formEstudante->get('estado'));
                ?>
            </div>

            <label for="inputCep" class="col-lg-1 col-md-1 control-label">Cep:</label>
            <div class="col-lg-2 col-md-2">
                <?php
                // renderiza html input
                echo $this->formInput($formEstudante->get('cep'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formEstudante->get('cep'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputEmail" class="col-lg-2 col-md-2 control-label">Email*:</label>
            <div class="col-lg-5 col-md-5">
                <?php
                // renderiza html input
                echo $this->formInput($formEstudante->get('email'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formEstudante->get('email'));
                ?>
            </div>

            <label for="inputDataNasc" class="col-lg-2 col-md-2 control-label">Data de Nascimento*:</label>
            <div class="col-lg-3 col-md-3">
                <?php
                // renderiza html input
                echo $this->formInput($formEstudante->get('data_nasc'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formEstudante->get('data_nasc'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputTelefonePrincipal" class="col-lg-2 col-md-2 control-label">Tel. Principal*:</label>
            <div class="col-lg-4  col-md-4">
                <?php
                // renderiza html input
                echo $this->formInput($formEstudante->get('telefone_principal'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formEstudante->get('telefone_principal'));
                ?>
            </div>

            <label for="inputTelefoneSecundario" class="col-lg-2 col-md-2 control-label">Tel. Secundário:</label>
            <div class="col-lg-4  col-md-4">
                <?php
                // renderiza html input
                echo $this->formInput($formEstudante->get('telefone_secundario'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formEstudante->get('telefone_secundario'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="radSexo" class="col-lg-2 col-md-2 control-label">Sexo*:</label>
            <div class="col-lg-2  col-md-2" id="radSexo">
                <?php
                // renderiza html input
                echo $this->FormRadio($formEstudante->get('sexo'));//colocar como name no form.php

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formEstudante->get('sexo'));
                ?>
            </div>

            <label for="radSituacao" class="col-lg-4 col-md-4 control-label">Situacao Atual*:</label>
            <div class="col-lg-1  col-md-1" id="radSituacao">
                <?php
                // renderiza html input
                echo $this->FormRadio($formEstudante->get('situacao'));//colocar como name no form.php

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formEstudante->get('situacao'));
                ?>
            </div>
        </div>

        <!--<div class="form-group">
            <label for="inputCaptcha" class="col-lg-3 col-md-3 control-label">Verificação*:</label>
            <div class="col-lg-9  col-md-9" id="captcha">
                <?php
                // renderiza captcha
                /*echo $this->formCaptcha(formEstudante->get('captcha'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render(formEstudante->get('captcha'));*/
                ?>
            </div>
        </div>-->
    </div>
    <div class="panel-footer">
        <?php
        // renderiza html input hidden para id
        echo $this->formHidden($formEstudante->get('id'));
        // renderiza html input hidden csrf
        //echo $this->formElement($formEstudante->get('security'));
        ?>

        <button type="submit" class="btn btn-primary">Salvar Contato</button>
        <a href="<?php echo $this->url('main'); ?>" class="btn btn-default">Voltar</a>
    </div>

    <?php // renderiza html </form> ?>
    <?php echo $this->form()->closeTag() ?>
</div>