<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Dados Pessoais
        </div>
    </div>
    <?php
    // objeto form contato
    $formMaterias = $this->formMaterias;
    // preparar elementos do formulário
    $formMaterias->prepare();
    // configurar url formulário
    $formMaterias->setAttribute('action', $this->url('main', array('action' => 'adicionarmateria')));
    ?>

    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($formMaterias) ?>
    <div class="panel-body">
        <div class="form-group">
            <label for="inputNomeMateria" class="col-lg-2 col-md-2 control-label">Nome Da Matéria*:</label>
            <div class="col-lg-10 col-md-10">
                <?php
                // renderiza html input
                echo $this->formInput($formMaterias->get('nome_materia'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formMaterias->get('nome_materia'));
                ?>
            </div>

            <label for="inputNomeProfessor" class="col-lg-2 col-md-2 control-label">Nome Do Professor*:</label>
            <div class="col-lg-10 col-md-10">
                <?php
                // renderiza html input
                echo $this->formInput($formMaterias->get('nome_professor'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formMaterias->get('nome_professor'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputAno" class="col-lg-2 col-md-2 control-label">Turno*:</label>
            <div class="col-lg-4 col-md-4">
                <?php
                // renderiza html input
                echo $this->formInput($formMaterias->get('ano'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formMaterias->get('ano'));
                ?>
            </div>

            <label for="inputTipo" class="col-lg-2 col-md-2 control-label">Tipo de Curso*:</label>
            <div class="col-lg-4 col-md-4">
                <?php
                // renderiza html input
                echo $this->formSelect($formMaterias->get('tipo_materia'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formMaterias->get('tipo_materia'));
                ?>
            </div>
        </div>


        <!--<div class="form-group">
            <label for="inputCaptcha" class="col-lg-2 col-md-2 control-label">Verificação*:</label>
            <div class="col-lg-9  col-md-9" id="captcha">
                <?php
        // renderiza captcha
        /*echo $this->formCaptcha($formMaterias->get('captcha'));

        // renderiza elemento de erro
        echo $this->formElementErrors()
            ->setMessageOpenFormat('<small class="text-danger">')
            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
            ->setMessageCloseString('</small>')
            ->render(formDadosPessoais->get('captcha'));*/
        ?>
            </div>
        </div>-->
    </div>
    <div class="panel-footer">
        <?php
        // renderiza html input hidden para id
        echo $this->formHidden($formMaterias->get('id_materia'));
        // renderiza html input hidden csrf
        //echo $this->formElement($formMaterias->get('security'));
        ?>

        <button type="submit" class="btn btn-primary">Salvar Dados</button>
        <a href="<?php echo $this->url('main'); ?>" class="btn btn-default">Voltar</a>
    </div>

    <?php // renderiza html </form> ?>
    <?php echo $this->form()->closeTag() ?>
</div>