<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Novo Série
        </div>
    </div>
    <?php
    // objeto form contato
    $formSeries = $this->formSeries;
    // preparar elementos do formulário
    $formSeries->prepare();
    // configurar url formulário
    $formSeries->setAttribute('action', $this->url('main', array('action' => 'adicionarserie')));
    ?>

    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($formSeries) ?>
    <div class="panel-body">
        <div class="form-group">
            <label for="inputNomeSerie" class="col-lg-2 col-md-2 control-label">Nome da Série*:</label>
            <div class="col-lg-10 col-md-10">
                <?php
                // renderiza html input
                echo $this->formInput($formSeries->get('nome_serie'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formSeries->get('nome_serie'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputSubtipo" class="col-lg-2 col-md-2 control-label">Subtipo da Série*:</label>
            <div class="col-lg-4 col-md-4">
                <?php
                // renderiza html input
                echo $this->formRadio($formSeries->get('subtipo'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formSeries->get('subtipo'));
                ?>
            </div>
        </div>


        <!--<div class="form-group">
            <label for="inputCaptcha" class="col-lg-2 col-md-2 control-label">Verificação*:</label>
            <div class="col-lg-9  col-md-9" id="captcha">
                <?php
        // renderiza captcha
        /*echo $this->formCaptcha(formDadosPessoais->get('captcha'));

        // renderiza elemento de erro
        echo $this->formElementErrors()
            ->setMessageOpenFormat('<small class="text-danger">')
            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
            ->setMessageCloseString('</small>')
            ->render(formDadosPessoais->get('captcha'));*/
        ?>
            </div>
        </div>-->
    </div>
    <div class="panel-footer">
        <?php
        // renderiza html input hidden para id
        echo $this->formHidden($formSeries->get('id_serie'));
        // renderiza html input hidden csrf
        //echo $this->formElement($formSeries->get('security'));
        ?>

        <button type="submit" class="btn btn-primary">Salvar Dados</button>
        <a href="<?php echo $this->url('main'); ?>" class="btn btn-default">Voltar</a>
    </div>

    <?php // renderiza html </form> ?>
    <?php echo $this->form()->closeTag() ?>
</div>