<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Novo Aluno
        </div>
    </div>
    <?php
    // objeto form contato
    $formAlunos = $this->formAlunos;
    // preparar elementos do formulário
    $formAlunos->prepare();
    // configurar url formulário
    $formAlunos->setAttribute('action', $this->url('main', array('action' => 'adicionaraluno')));
    ?>

    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($formAlunos) ?>
    <div class="panel-body">
        <div class="form-group">
            <label for="inputNomeAluno" class="col-lg-2 col-md-2 control-label">Nome Do Aluno*:</label>
            <div class="col-lg-6 col-md-6">
                <?php
                // renderiza html input
                echo $this->formInput($formAlunos->get('nome_aluno'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formAlunos->get('nome_aluno'));
                ?>
            </div>

            <label for="inputMatriculaAluno" class="col-lg-1 col-md-1 control-label">Matrícula*:</label>
            <div class="col-lg-3 col-md-3">
                <?php
                // renderiza html input
                echo $this->formInput($formAlunos->get('matricula_aluno'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formAlunos->get('matricula_aluno'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputCursoAluno" class="col-lg-2 col-md-2 control-label">Curso*:</label>
            <div class="col-lg-4 col-md-4">
                <?php
                // renderiza html input
                echo $this->formSelect($formAlunos->get('curso_aluno'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formAlunos->get('curso_aluno'));
                ?>
            </div>

            <label for="inputSerieAluno" class="col-lg-2 col-md-2 control-label">Série*:</label>
            <div class="col-lg-4 col-md-4">
                <?php
                // renderiza html input
                echo $this->formSelect($formAlunos->get('serie_aluno'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formAlunos->get('serie_aluno'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputMateriaAluno" class="col-lg-2 col-md-2 control-label">Matéria*:</label>
            <div class="col-lg-4 col-md-4">
                <?php
                // renderiza html input
                echo $this->formSelect($formAlunos->get('materia_aluno'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formAlunos->get('materia_aluno'));
                ?>
            </div>

            <label for="inputProfessorAluno" class="col-lg-2 col-md-2 control-label">Professor*:</label>
            <div class="col-lg-4 col-md-4">
                <?php
                // renderiza html input
                echo $this->formSelect($formAlunos->get('professor_aluno'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formAlunos->get('professor_aluno'));
                ?>
            </div>
        </div>


        <!--<div class="form-group">
            <label for="inputCaptcha" class="col-lg-2 col-md-2 control-label">Verificação*:</label>
            <div class="col-lg-9  col-md-9" id="captcha">
                <?php
        // renderiza captcha
        /*echo $this->formCaptcha(formDadosPessoais->get('captcha'));

        // renderiza elemento de erro
        echo $this->formElementErrors()
            ->setMessageOpenFormat('<small class="text-danger">')
            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
            ->setMessageCloseString('</small>')
            ->render(formDadosPessoais->get('captcha'));*/
        ?>
            </div>
        </div>-->
    </div>
    <div class="panel-footer">
        <?php
        // renderiza html input hidden para id
        echo $this->formHidden($formAlunos->get('id_aluno'));
        // renderiza html input hidden csrf
        //echo $this->formElement($formAlunos->get('security'));
        ?>

        <button type="submit" class="btn btn-primary">Salvar Dados</button>
        <a href="<?php echo $this->url('main'); ?>" class="btn btn-default">Voltar</a>
    </div>

    <?php // renderiza html </form> ?>
    <?php echo $this->form()->closeTag() ?>
</div>