<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Dados Pessoais
        </div>
    </div>
    <?php
    // objeto form contato
    $formCursos = $this->formCursos;
    // preparar elementos do formulário
    $formCursos->prepare();
    // configurar url formulário
    $formCursos->setAttribute('action', $this->url('main', array('action' => 'adicionarcurso')));
    ?>

    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($formCursos) ?>
    <div class="panel-body">
        <div class="form-group">
            <label for="inputNomeCurso" class="col-lg-2 col-md-2 control-label">Nome Do Curso*:</label>
            <div class="col-lg-10 col-md-10">
                <?php
                // renderiza html input
                echo $this->formInput($formCursos->get('nome_curso'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formCursos->get('nome_curso'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputTurno" class="col-lg-2 col-md-2 control-label">Turno*:</label>
            <div class="col-lg-4 col-md-4">
                <?php
                // renderiza html input
                echo $this->formRadio($formCursos->get('turno'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formCursos->get('turno'));
                ?>
            </div>

            <label for="inputTipo" class="col-lg-2 col-md-2 control-label">Tipo de Curso*:</label>
            <div class="col-lg-4 col-md-4">
                <?php
                // renderiza html input
                echo $this->formRadio($formCursos->get('tipo'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formCursos->get('tipo'));
                ?>
            </div>
        </div>


        <!--<div class="form-group">
            <label for="inputCaptcha" class="col-lg-2 col-md-2 control-label">Verificação*:</label>
            <div class="col-lg-9  col-md-9" id="captcha">
                <?php
        // renderiza captcha
        /*echo $this->formCaptcha(formDadosPessoais->get('captcha'));

        // renderiza elemento de erro
        echo $this->formElementErrors()
            ->setMessageOpenFormat('<small class="text-danger">')
            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
            ->setMessageCloseString('</small>')
            ->render(formDadosPessoais->get('captcha'));*/
        ?>
            </div>
        </div>-->
    </div>
    <div class="panel-footer">
        <?php
        // renderiza html input hidden para id
        echo $this->formHidden($formCursos->get('id_curso'));
        // renderiza html input hidden csrf
        //echo $this->formElement($formCursos->get('security'));
        ?>

        <button type="submit" class="btn btn-primary">Salvar Dados</button>
        <a href="<?php echo $this->url('main'); ?>" class="btn btn-default">Voltar</a>
    </div>

    <?php // renderiza html </form> ?>
    <?php echo $this->form()->closeTag() ?>
</div>