<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Novo Funcionário
        </div>
    </div>
    <?php
    // objeto form contato
    $formFuncionarios = $this->formFuncionarios;
    // preparar elementos do formulário
    $formFuncionarios->prepare();
    // configurar url formulário
    $formFuncionarios->setAttribute('action', $this->url('main', array('action' => 'adicionarfuncionario')));
    ?>

    <?php // renderiza html <form> com atributos configurados no objeto ?>
    <?php echo $this->form()->openTag($formFuncionarios) ?>
    <div class="panel-body">
        <div class="form-group">
            <label for="inputNomeFuncionario" class="col-lg-2 col-md-2 control-label">Nome do Funcionario*:</label>
            <div class="col-lg-9 col-md-9">
                <?php
                // renderiza html input
                echo $this->formInput($formFuncionarios->get('nome_funcionario'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formFuncionarios->get('nome_funcionario'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputFormacao" class="col-lg-2 col-md-2 control-label">Formacao*:</label>
            <div class="col-lg-5 col-md-5">
                <?php
                // renderiza html input
                echo $this->formInput($formFuncionarios->get('formacao'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formFuncionarios->get('formacao'));
                ?>
            </div>

            <label for="inputCargoFuncionario" class="col-lg-1 col-md-1 control-label">Cargo*:</label>
            <div class="col-lg-3 col-md-3">
                <?php
                // renderiza html input
                echo $this->formSelect($formFuncionarios->get('cargo_funcionario'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formFuncionarios->get('cargo_funcionario'));
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="inputEspecialidade" class="col-lg-2 col-md-2 control-label">Especialidade(s)*:</label>
            <div class="col-lg-9 col-md-9">
                <?php
                // renderiza html input
                echo $this->formTextarea($formFuncionarios->get('especialidade'));

                // renderiza elemento de erro
                echo $this->formElementErrors()
                    ->setMessageOpenFormat('<small class="text-danger">')
                    ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                    ->setMessageCloseString('</small>')
                    ->render($formFuncionarios->get('especialidade'));
                ?>
            </div>
        </div>


        <!--<div class="form-group">
            <label for="inputCaptcha" class="col-lg-2 col-md-2 control-label">Verificação*:</label>
            <div class="col-lg-9  col-md-9" id="captcha">
                <?php
        // renderiza captcha
        /*echo $this->formCaptcha(formDadosPessoais->get('captcha'));

        // renderiza elemento de erro
        echo $this->formElementErrors()
            ->setMessageOpenFormat('<small class="text-danger">')
            ->setMessageSeparatorString('</small><br/><small class="text-danger">')
            ->setMessageCloseString('</small>')
            ->render(formDadosPessoais->get('captcha'));*/
        ?>
            </div>
        </div>-->
    </div>
    <div class="panel-footer">
        <?php
        // renderiza html input hidden para id
        echo $this->formHidden($formFuncionarios->get('id_funcionario'));
        // renderiza html input hidden csrf
        //echo $this->formElement($formFuncionarios->get('security'));
        ?>

        <button type="submit" class="btn btn-primary">Salvar Dados</button>
        <a href="<?php echo $this->url('main'); ?>" class="btn btn-default">Voltar</a>
    </div>

    <?php // renderiza html </form> ?>
    <?php echo $this->form()->closeTag() ?>
</div>