<?php
/**
 * Created by PhpStorm.
 * User: CristianoGD
 * Date: 12/10/2015
 * Time: 15:24
 */
?>

<div class="row">
    <div class="col-md-4">
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Sistema de Login') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('O Sistema ira permitir ao estudante ao logar verificar suas notas e ao funcionario gerenciar dados do sistema.'), '<a href="#login_usuario">', '</a>') ?></p>

                <form role="form" method="post" action="/main">
                    <div class="form-group">
                        <label for="inputEmail">Email</label>
                        <input type="email" class="form-control" id="inputEmail" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <label for="inputPassword">Password</label>
                        <input type="password" class="form-control" id="inputPassword" placeholder="Password">
                    </div>
                    <div class="checkbox">
                        <label><input type="checkbox"> Remember me</label>
                    </div>
                    <button type="submit" class="btn btn-primary">Login</button>
                </form>
            </div>
        </div>
    </div>

    <div class="col-md-4">
    </div>
</div>